### ISSUE TITLE
I am getting an error message

### ISSUE THREAD

**Issue by Kiki1022** [learn-co-curriculum/js-what-is-a-test#33]
[14:37:05] (master) js-what-is-a-test-bootcamp-prep-000
// ♥ node js/index.js
module.js:550
    throw err;
    ^

Error: Cannot find module '/home/elegant-delimiter-3950/js-what-is-a-test-bootcamp-prep-000/js/index.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
[14:38:59] (master) js-what-is-a-test-bootcamp-prep-000
// ♥

**Comment by lizbur10** [comment]
Thank you for providing feedback. We have clarified the lab instructions to address this issue.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
